apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-app
spec:
  selector:
    matchLabels:
      app: go-test-app
  template:
    metadata:
      labels:
        app: go-test-app
    spec:
      containers:
      - name: go-test-app
        image: nitincg/testgo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
